apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::188630578400:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1VXM4D2UXMPNF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::188630578400:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-16T21:44:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1268"
  uid: da080da8-850d-4879-903a-ea0b87bbd4d2
